### ISSUE TITLE
6 month and 2 year email content

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-contacts-scheduler#9]

**Comment by LucieGueuning** [comment]
1. Could you please send those email to me, so that I can confirm from the user perspective? 
2. Can you confirm that you base those reminder on contact perspective and use of REACH and not every 6 months from the platform creation. Right?

**Comment by matthewberryman** [comment]
1. Will do shortly.
2. I will answer on #8 as that's more to do with the algorithms and user behaviour (also related to 2 year cycle).
